### ISSUE TITLE
unexpected keyword argument 'training'

### ISSUE THREAD

**Issue by parsifal9** [aruberts/blogs#1]
Hi aruberts ,

I copied this page and tried working through it.
All seems to go well until I get to tabnet.fit when I get an error 
```
unexpected keyword argument 'training'
```
I did not do the optimization, just used your training parameters. 
Here it the full error message. 

```
>>> tabnet.fit(train_ds, 
...            epochs=1000, 
...            validation_data=val_ds,
...            callbacks=cbs,
...            verbose=1,
...           class_weight={
...               0:1,
...               1: 10
...           })
Epoch 1/1000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch1/dun280/tabnet/script4.Rmd", line 735, in <module>
    Epoch 6/1000
  File "/scratch1/dun280/python_virtual_envs/env2/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/dun280.vnc/__autograph_generated_fileuzwxo4d5.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/tmp/dun280.vnc/__autograph_generated_file73u3_d4p.py", line 80, in tf__call
    ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(self).n_step + 1,), None, fscope), None, loop_body, get_state_2, set_state_2, ('importance', 'out', 'total_entropy', 'mask_values', 'masked_features', 'out_agg', 'prior_scales'), {'iterate_names': 'step_i'})
  File "/tmp/dun280.vnc/__autograph_generated_file73u3_d4p.py", line 29, in loop_body
    x = ag__.converted_call(ag__.ld(self).feature_transforms[ag__.ld(step_i)], (ag__.ld(masked_features),), dict(training=ag__.ld(training)), fscope)
TypeError: in user code:

    File "/scratch1/dun280/python_virtual_envs/env2/lib/python3.9/site-packages/keras/engine/training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "/scratch1/dun280/python_virtual_envs/env2/lib/python3.9/site-packages/keras/engine/training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/scratch1/dun280/python_virtual_envs/env2/lib/python3.9/site-packages/keras/engine/training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "/scratch1/dun280/python_virtual_envs/env2/lib/python3.9/site-packages/keras/engine/training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "/scratch1/dun280/python_virtual_envs/env2/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/dun280.vnc/__autograph_generated_file73u3_d4p.py", line 80, in tf__call
        ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(self).n_step + 1,), None, fscope), None, loop_body, get_state_2, set_state_2, ('importance', 'out', 'total_entropy', 'mask_values', 'masked_features', 'out_agg', 'prior_scales'), {'iterate_names': 'step_i'})
    File "/tmp/dun280.vnc/__autograph_generated_file73u3_d4p.py", line 29, in loop_body
        x = ag__.converted_call(ag__.ld(self).feature_transforms[ag__.ld(step_i)], (ag__.ld(masked_features),), dict(training=ag__.ld(training)), fscope)

    TypeError: Exception encountered when calling layer "tab_net" "                 f"(type TabNet).
    
    in user code:
    
        File "/scratch1/dun280/tabnet/script4.Rmd", line 571, in call  *
            x = self.feature_transforms[step_i](
        File "/scratch1/dun280/python_virtual_envs/env2/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
    
        TypeError: Exception encountered when calling layer "feature_transformer" "                 f"(type FeatureTransformer).
        
        in user code:
        
        
            TypeError: tf__shared_fcs() got an unexpected keyword argument 'training'
        
        
        Call arguments received by layer "feature_transformer" "                 f"(type FeatureTransformer):
          • x=tf.Tensor(shape=(None, 420), dtype=float32)
          • training=True
    
    
    Call arguments received by layer "tab_net" "                 f"(type TabNet):
      • features=tf.Tensor(shape=(None, 420), dtype=float32)
      • training=True
```
Bye
R

**Comment by parsifal9** [comment]
Hi aruberts ,

this just worked on another machine. 
I can't understand why (same commands to set up the env), but the problem is gone. I will try to figure out what caused it, perhaps the wrong version of something is being picked up. If I figure it out I will post here, otherwise I will close the issue.
Thanks for posting the code. It has been very helpful
R

**Comment by parsifal9** [comment]
removing ~./local fixed it. Must be an incompatible version of something.
Closing the issue
thanks
Bye
